In [226]:
from __future__ import print_function
import torch

In [227]:
x = torch.Tensor(5,3)
print(x)


1.00000e-13 *
 -6.4537  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]



In [228]:
x = torch.rand(5, 3)
print(x)


 0.4717  0.3127  0.2827
 0.0726  0.4214  0.4066
 0.0405  0.4677  0.6024
 0.7655  0.3604  0.5716
 0.8888  0.1335  0.5792
[torch.FloatTensor of size 5x3]



In [229]:
print(x.size())

torch.Size([5, 3])


In [230]:
y = torch.rand(5, 3)
print(x+y)


 0.6452  0.4214  1.0407
 0.8135  0.8776  0.7576
 0.5146  0.6444  1.5800
 1.6240  1.2414  0.6307
 1.5562  0.8765  1.5295
[torch.FloatTensor of size 5x3]



In [231]:
print(torch.add(x, y))


 0.6452  0.4214  1.0407
 0.8135  0.8776  0.7576
 0.5146  0.6444  1.5800
 1.6240  1.2414  0.6307
 1.5562  0.8765  1.5295
[torch.FloatTensor of size 5x3]



In [232]:
result = torch.Tensor(5, 3)
torch.add(x, y, out = result)
print(result)


 0.6452  0.4214  1.0407
 0.8135  0.8776  0.7576
 0.5146  0.6444  1.5800
 1.6240  1.2414  0.6307
 1.5562  0.8765  1.5295
[torch.FloatTensor of size 5x3]



In [233]:
y.add_(x)
print(y)


 0.6452  0.4214  1.0407
 0.8135  0.8776  0.7576
 0.5146  0.6444  1.5800
 1.6240  1.2414  0.6307
 1.5562  0.8765  1.5295
[torch.FloatTensor of size 5x3]



In [234]:
print(x[ : , 1])
print(x[:2,1])


 0.3127
 0.4214
 0.4677
 0.3604
 0.1335
[torch.FloatTensor of size 5]


 0.3127
 0.4214
[torch.FloatTensor of size 2]



In [235]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [236]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [237]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [238]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [239]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [240]:
from torch.autograd import Variable

In [241]:
x = Variable(torch.ones(2,2), requires_grad = True)
print(x)
print(x.grad)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

None


In [242]:
y = x + 2
print(y)

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [243]:
print(y.grad_fn)

In [244]:
z = y * y * 3
out = z.mean()
print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [245]:
out.backward()
print(out)

Variable containing:
 27
[torch.FloatTensor of size 1]



In [246]:
print(x.grad)

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



In [247]:
x = torch.rand(3)
x = Variable(x, requires_grad = True)
y = x * 2
while (y.data.norm() < 1000):
    y = y * 2
print(y)


Variable containing:
  615.1584
 1362.3973
  764.6960
[torch.FloatTensor of size 3]



In [248]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
print(x.grad)

Variable containing:
  204.8000
 2048.0000
    0.2048
[torch.FloatTensor of size 3]



# Neural Network:
Step-1: Define the Network

In [249]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:] 
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)


Net (
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear (400 -> 120)
  (fc2): Linear (120 -> 84)
  (fc3): Linear (84 -> 10)
)


In [250]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 5, 5])


In [251]:
input = Variable(torch.rand(1, 1, 32, 32))
out = net(input)
print(out)

Variable containing:
1.00000e-02 *
  7.5127  9.0654  8.3067  6.4209  0.0105 -6.4171 -5.4940 -9.2106 -4.9905  3.7880
[torch.FloatTensor of size 1x10]



In [252]:
net.zero_grad()
out.backward(torch.randn(1, 10))

# Loss function

In [253]:
output = net(input)
target = Variable(torch.arange(1, 11))
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

Variable containing:
 38.6672
[torch.FloatTensor of size 1]



In [254]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

# Back Propogation
loss.backward()

In [255]:
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
Variable containing:
 0
 0
 0
 0
 0
 0
[torch.FloatTensor of size 6]

conv1.bias.grad after backward
Variable containing:
1.00000e-02 *
  2.9687
 -3.1159
 -7.0976
  7.7624
  5.3754
 -4.9381
[torch.FloatTensor of size 6]



# Updating the weights of Network

In [256]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate) #inplace substraction


In [257]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr = 0.01)

optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()

# Training the nNeural net with Dats

In [258]:
import torch
import torchvision
import torchvision.transforms as transforms

In [259]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)

testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

Files already downloaded and verified
Files already downloaded and verified


In [260]:
import matplotlib.pyplot as plt
import numpy as np

def imshow(img):
    img = img / 2 + 5
    npimg = img.numpy()
    
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    
dataiter = iter(trainloader)
images, labels = dataiter.next()

imshow(torchvision.utils.make_grid(images))

print(' '.join('%5s' % classes[labels[j]] for j in range(4)))
    

 ship   cat  frog plane


In [261]:
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()

In [262]:
import torch.optim as optim
criterion = nn.CrossEntropyLoss()

optimizer = optim.SGD(net.parameters(), lr=0.001, momentum = 0.9)


In [263]:
for epoch in range(2):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        
        inputs, labels = Variable(inputs), Variable(labels)
        
        optimizer.zero_grad()
        
        outputs = net(inputs)
        
        loss = criterion(outputs, labels)
        loss.backward()
        
        optimizer.step()
        
        running_loss += loss.data[0]
        
        if i % 2000 == 1999:
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0
            
print('Finished Training')

[1,  2000] loss: 2.240
[1,  4000] loss: 1.866
[1,  6000] loss: 1.682
[1,  8000] loss: 1.568
[1, 10000] loss: 1.524
[1, 12000] loss: 1.469
[2,  2000] loss: 1.389
[2,  4000] loss: 1.374
[2,  6000] loss: 1.338
[2,  8000] loss: 1.326
[2, 10000] loss: 1.302
[2, 12000] loss: 1.279
Finished Training


In [264]:
dataiter = iter(testloader)
images, labels = dataiter.next()

# print images
imshow(torchvision.utils.make_grid(images))
print('GroundTruth: ', ' '.join('%5s' % classes[labels[j]] for j in range(4)))

GroundTruth:    cat  ship  ship plane


In [265]:
outputs = net(Variable(images))

In [266]:
_, predicted = torch.max(outputs.data, 1)

print('Predicted: ', ' '.join('%5s' % classes[predicted[j]]
                              for j in range(4)))


Predicted:    cat  ship   car plane


In [267]:
correct = 0
total = 0
for data in testloader:
    images, labels = data
    outputs = net(Variable(images))
    _, predicted = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (predicted == labels).sum()

print('Accuracy of the network on the 10000 test images: %d %%' % (
    100 * correct / total))

Accuracy of the network on the 10000 test images: 53 %


In [268]:
class_correct = list(0. for i in range(10))
class_total = list(0. for i in range(10))
for data in testloader:
    images, labels = data
    outputs = net(Variable(images))
    _, predicted = torch.max(outputs.data, 1)
    c = (predicted == labels).squeeze()
    for i in range(4):
        label = labels[i]
        class_correct[label] += c[i]
        class_total[label] += 1


for i in range(10):
    print('Accuracy of %5s : %2d %%' % (
        classes[i], 100 * class_correct[i] / class_total[i]))

Accuracy of plane : 70 %
Accuracy of   car : 63 %
Accuracy of  bird : 53 %
Accuracy of   cat : 30 %
Accuracy of  deer : 41 %
Accuracy of   dog : 57 %
Accuracy of  frog : 67 %
Accuracy of horse : 55 %
Accuracy of  ship : 49 %
Accuracy of truck : 49 %
